# Generated by Django 5.2.6 on 2025-09-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('ANIMATION', 'Animation'), ('THRILLER', 'Thriller'), ('ROMANCE', 'Romance'), ('MYSTERY', 'Mystery'), ('CRIME', 'Crime'), ('FANTASY', 'Fantasy'), ('HISTORICAL', 'Historical'), ('WAR', 'War'), ('SPORTS', 'Sports'), ('SCI-FI', 'Sci-Fi')], default='ACTION', max_length=20),
        ),
    ]
