# Generated by Django 5.2.6 on 2025-09-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='birthday',
        ),
    ]
